// SLSA Build Track level assessor (altais_assess_slsa_level).
//
// Determines the achieved SLSA v1.2 Build Track level (0-3) from a set
// of boolean build-process facts, emits a finding stating the current
// level, and lists the exact requirements still needed to reach the
// next level.

import type { Finding } from "../../core/types.js";
import { buildSdlcFinding } from "./finding.js";

export interface SlsaConfig {
  readonly scripted_build?: boolean;
  readonly build_service?: boolean;
  readonly provenance_generated?: boolean;
  readonly provenance_authenticated?: boolean;
  readonly provenance_service_generated?: boolean;
  readonly isolated_build?: boolean;
  readonly hermetic?: boolean;
  readonly parameterless?: boolean;
}

export interface SlsaAssessInput {
  readonly config: SlsaConfig;
  readonly filename?: string;
}

const REFS = [
  "https://slsa.dev/spec/v1.2/levels",
  "https://slsa.dev/spec/v1.2/requirements",
  "https://cwe.mitre.org/data/definitions/1357.html",
];

export interface SlsaAssessment {
  readonly level: 0 | 1 | 2 | 3;
  readonly next_level: 1 | 2 | 3 | null;
  readonly missing_for_next: readonly string[];
}

interface LevelRequirement {
  readonly level: 1 | 2 | 3;
  readonly key: keyof SlsaConfig;
  readonly requirement: string;
}

// SLSA v1.2 Build Track requirements, cumulative by level.
const REQUIREMENTS: readonly LevelRequirement[] = [
  {
    level: 1,
    key: "scripted_build",
    requirement: "L1: the build runs from a consistent build script (not ad-hoc manual steps).",
  },
  {
    level: 1,
    key: "provenance_generated",
    requirement: "L1: provenance describing how the artifact was built is generated.",
  },
  {
    level: 2,
    key: "build_service",
    requirement: "L2: the build runs on a hosted, managed build service (not a developer machine).",
  },
  {
    level: 2,
    key: "provenance_service_generated",
    requirement:
      "L2: provenance is generated by the build service, not by user-controlled build steps.",
  },
  {
    level: 2,
    key: "provenance_authenticated",
    requirement: "L2: provenance is authenticated — signed so consumers can verify it is genuine.",
  },
  {
    level: 3,
    key: "isolated_build",
    requirement:
      "L3: builds run in an isolated environment with no cross-build influence or secret leakage.",
  },
  {
    level: 3,
    key: "hermetic",
    requirement:
      "L3: the build is hermetic — all dependencies are declared up front and fetched into the isolated environment.",
  },
  {
    level: 3,
    key: "parameterless",
    requirement:
      "L3: the build is parameterless — its behavior is fully defined by the source, with no external build parameters.",
  },
];

function levelSatisfied(config: SlsaConfig, level: 1 | 2 | 3): boolean {
  return REQUIREMENTS.filter((r) => r.level <= level).every((r) => config[r.key] === true);
}

/** Assess the achieved SLSA v1.2 Build Track level from build-process facts. */
export function assessSlsa(config: SlsaConfig): SlsaAssessment {
  let level: 0 | 1 | 2 | 3 = 0;
  if (levelSatisfied(config, 1)) level = 1;
  if (level === 1 && levelSatisfied(config, 2)) level = 2;
  if (level === 2 && levelSatisfied(config, 3)) level = 3;

  const nextLevel: 1 | 2 | 3 | null = level === 3 ? null : ((level + 1) as 1 | 2 | 3);
  const missing: string[] =
    nextLevel === null
      ? []
      : REQUIREMENTS.filter((r) => r.level <= nextLevel && config[r.key] !== true).map(
          (r) => r.requirement,
        );

  return { level, next_level: nextLevel, missing_for_next: missing };
}

export function assessSlsaLevel(input: SlsaAssessInput): readonly Finding[] {
  const assessment = assessSlsa(input.config);
  const { level, next_level: nextLevel, missing_for_next: missing } = assessment;

  const severity: Finding["severity"] =
    level === 0 ? "high" : level === 1 ? "medium" : level === 2 ? "low" : "info";

  const nextText =
    nextLevel === null
      ? "The build already meets SLSA v1.2 Build Track Level 3, the highest level."
      : `To reach SLSA Build Track Level ${String(nextLevel)}, satisfy: ${missing.join(" ")}`;

  const description =
    level === 3
      ? "The build process meets SLSA v1.2 Build Track Level 3: it is scripted, runs on a hosted build service that generates signed provenance, and is isolated, hermetic, and parameterless."
      : `The build process meets SLSA v1.2 Build Track Level ${String(level)}. ${nextText}`;

  const remediation =
    nextLevel === null
      ? "Maintain the Level 3 controls and verify provenance on every consumer install."
      : `Implement the missing Level ${String(nextLevel)} requirements: ${missing.join(" ")}`;

  const finding = buildSdlcFinding(
    {
      rule: `slsa-build-track-level-${String(level)}`,
      severity,
      title: `Build process is at SLSA v1.2 Build Track Level ${String(level)}`,
      description,
      remediation,
      cwe: ["CWE-1357", "CWE-345"],
      references: REFS,
      evidence: `slsa_level=${String(level)}${nextLevel !== null ? `; next=L${String(nextLevel)}` : ""}`,
      tags: ["slsa", "supply-chain", `level-${String(level)}`],
    },
    input.filename,
  );

  return [finding];
}
